name: flutter_hms_scankit
description: 华为统一扫码服务 Flutter版本
version: 1.2.4
homepage: https://github.com/L-X-J/flutter-hms-scankit

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: xyz.icxl.flutter.hms.scan
        pluginClass: FlutterScankitPlugin
      ios:
        pluginClass: FlutterScankitPlugin

# /Users/chenxinlei/FlutterProjects/flutter-hms-scankit/android/src/main/java/xyz/icxl/fluter/hms/scan
# /Users/chenxinlei/FlutterProjects/flutter-hms-scankit/android/src/main/java/xyz/icxl/flutter/hms/scan