name: flutter_hms_scankit
description: The Flutter version of Huawei's unified scanning service, and the iOS version uses the SGQRCODE scanning library.
homepage: https://github.com/L-X-J/flutter-hms-scankit
publish_to: none
version: 1.6.0
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: xyz.icxl.flutter.hms.scan
        pluginClass: FlutterScankitPlugin
      ios:
        pluginClass: FlutterScankitPlugin
