name: flutter_hms_scankit
description: 华为统一扫码服务 Flutter版本，iOS为SGQRCODE扫码库
version: 1.6.0
homepage: https://github.com/L-X-J/flutter-hms-scankit
publish_to: none
environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: xyz.icxl.flutter.hms.scan
        pluginClass: FlutterScankitPlugin
      ios:
        pluginClass: FlutterScankitPlugin